const appname = "Kikwadmin App",
    login = "Se connecter",
    welcome = "HI, Bienvenue sur",
    email = "Email",
    emailHint = "exple. vendeur@Konguil.com",
    password = "Mot de passe",
    passwordHint = "***********",
    forgotPassword = "Mot de passe oublié ?",
retypePassword = "Retaper mot de passe",
privacyPolicy = "Politique de confidentialité",
 termAndCond = "Termes et Conditions",
    signup = "S'inscrire",
    alreadyHaveAccount = "Avez-vous un compte ? ",
    createNewAccount = "ou, créer un nouveau compte",
dashboard = "Accueil",
products = "Produits",
settings = "Paramètres",
orders = "Commandes",
rating = "Soldes",
totalSales = "Vendus",
popular = "Produits populaires",
messages = "Messages",
logout = "Deconnecter",
changeImage = "Changer Image",
featured = "Recommandés",
save = "Enregistrer",
name = "Nom d'utilisateur",
edit = "Modifier",
confirmPass = "Confirmer mot de passer",
remove = "Supprimer",chat = "Chats",

shopSettings = "Paramètres",
loginTo = "Connectez-vous à votre compte",
    anyProblem = "En cas de difficultés, contactez RaabéTech", credit = "Développé par RaabeTech";

//shop settings strings
const nameHint = "nom du vendeur",
shopDescHint = "Saisir la description du l'article",
shopWebsiteHint = "monsite.com",
shopMobileHint = "ex: +23562400778",
shopAddressHint = "Avenue Kondol",
description = "Description de votre boutique",
mobile = "Shop mobile",
website = "Shop Website",
shopName = "Shop Name", address = "addresse boutique";
